emacs: fix rust "checkOnSave" error
Every time i saved a file from `rustic-mode`, i was getting this
error: `/checkOnSave: invalid type: map, expected a boolean;`. It was
coming from my eglot `rust-analyzer` config, which was using an older
style. Reworked to newer format that rust analyzer expects.